---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ztpfw-ui
  name: ztpfw-ui
  namespace: ___NAMESPACE___
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ztpfw-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ztpfw-ui
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: beta.kubernetes.io/arch
#                operator: In
#                values:
#                - amd64
#                - ppc64le
#                - s390x
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - podAffinityTerm:
#              labelSelector:
#                matchExpressions:
#                - key: ocm-antiaffinity-selector
#                  operator: In
#                  values:
#                  - console
#                - key: component
#                  operator: In
#                  values:
#                  - console
#              topologyKey: topology.kubernetes.io/zone
#            weight: 70
#          - podAffinityTerm:
#              labelSelector:
#                matchExpressions:
#                - key: ocm-antiaffinity-selector
#                  operator: In
#                  values:
#                  - console
#                - key: component
#                  operator: In
#                  values:
#                  - console
#              topologyKey: kubernetes.io/hostname
#            weight: 35
      containers:
      - env:
        - name: BACKEND_PORT
          value: "3000"
        - name: FRONTEND_URL
          value: "___APP_URL___"
        - name: CLUSTER_API_URL
          value: https://kubernetes.default.svc:443
        - name: OAUTH2_CLIENT_ID
          value: "ztpfwoauth"
        - name: OAUTH2_REDIRECT_URL
          value: "___APP_URL___/login/callback"
        - name: OAUTH2_CLIENT_SECRET
          value: "ztpfwoauthsecret"
        image: ___IMAGE___
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 3000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ztpfw-ui
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readinessProbe
            port: 3000
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 3m
            memory: 40Mi
        volumeMounts:
        - mountPath: /app/certs
          name: ztpfw-ui-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: ztpfw-ui-certs
        secret:
          defaultMode: 420
          secretName: ztpfw-ui-certs

---
apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  labels:
    app: ztpfw-ui
  name: ztpfwoauth
redirectURIs:
- ___APP_URL___/login/callback
secret: ztpfwoauthsecret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ztpfw-ui
  name: ztpfw-ui
  namespace: ___NAMESPACE___
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ztpfw-ui
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ztpfw-ui
  name: ztpfw-ui
  namespace: ___NAMESPACE___
spec:
  host: ___ROUTE_HOST___
  port:
    targetPort: https
  tls:
    # insecureEdgeTerminationPolicy: Redirect
    # termination: reencrypt
    termination: passthrough
  to:
    kind: Service
    name: ztpfw-ui
  wildcardPolicy: None
