apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: ztp-deploy-spoke
spec:
 workspaces:
  - name: ztp
 params:
  - name: ztp-tag
    type: string
    default: "latest"
  - name: config-file-path
    type: string
    default: ""
  - name: spokes-config
    type: string
    default: ""
 stepTemplate:
  env:
    - name: WORKDIR
      value: "/ztp-pipeline"
    - name: SPOKES_CONFIG
      value: $(params.spokes-config)
    - name: OUTPUTDIR
      value: $(workspaces.ztp.path)
    - name: KUBECONFIG
      value: "$(workspaces.ztp.path)/kubeconfig"

 steps:

   - name: deploy-metallb
     image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
     imagePullPolicy: Always
     script: |
      #!/usr/bin/env bash
      cd $WORKDIR/deploy-metallb
      ./deploy.sh
