---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
spec:
  channel: v1.10
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: ztpfw-catalog-certfied
  sourceNamespace: openshift-marketplace
  startingCSV: "gpu-operator-certified.v1.10.1"
