resources:
  - spoke-deploy-disconnected-registry-spokes.yaml
  - spoke-deploy-icsp-spokes-post.yaml
  - spoke-deploy-icsp-spokes-pre.yaml
  - spoke-deploy-metallb.yaml
  - spoke-deploy-ocs.yaml
  - spoke-deploy-spoke.yaml
  - spoke-deploy-spoke-sno.yaml
  - spoke-deploy-workers.yaml
  - spoke-detach-cluster.yaml
  - spoke-restore-hub-config.yaml
