- name: Update root user password
  user:
    name: root
    password: "{{ rootpassword }}"
    append: yes

- name: Set authorized keys for root
  authorized_key:
    user: root
    state: present
    exclusive: no
    key: "{{ item }}"
  with_items: "{{ sshkeys }}"

- name: Disable root login over ssh with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin .*"
    state: present
    line: "PermitRootLogin prohibit-password"
  notify:
    - Restart sshd

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication .*"
    state: present
    line: "PasswordAuthentication no"
  when: sshpassword==False
  notify:
    - Restart sshd

- name: Enable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication .*"
    state: present
    line: "PasswordAuthentication yes"
  when: sshpassword==True
  notify:
    - Restart sshd

- name: SSH Listen on all interfaces
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ListenAddress .*"
    state: absent
  notify:
    - Restart sshd
