name: deploy-ztp-spokes
on:
  workflow_dispatch:
    inputs:
      KUBECONFIG:
        description: 'Absolute path to KUBECONFIG file?'
        required: true
      SPOKES_FILE:
        description: 'Absolute path to the Spokes YAML file?'
        required: true
      RUNNER:
        description: 'GitHub Action Runner Tag'
        required: true
      SYNC:
        description: 'Force re-sync and mirror the Spokes? (yes/no)'
        default: no
        required: false


env:
  SYNC: ${{github.event.inputs.SYNC}}
  KUBECONFIG: ${{github.event.inputs.KUBECONFIG}}
  SPOKES_FILE: ${{github.event.inputs.SPOKES_FILE}}
  DEPLOY_ACM_DIR: deploy-acm
  DEPLOY_REGISTRY_DIR: deploy-disconnected-registry
  DEPLOY_HTTPD_SERVER_DIR: deploy-httpd-server
  DEPLOY_HUB_CONFIGS_DIR: deploy-hub-configs
  DEPLOY_SPOKES_DIR: deploy-spoke
  DEPLOY_WORKER_DIR: deploy-worker
  DEPLOY_OCS_DIR: deploy-ocs
  DEPLOY_POLICY_DIR: deploy-policies
  DEPLOY_METALLB_DIR: deploy-metallb
  FINISH_DEP_DIR: finish-deployment
  SHARED_DIR: shared-utils
  RO_SPOKE_FOLDER: /root/ztp-build-hub/


jobs:

  pre-flight:
    # continue-on-error: true
    runs-on: ${{github.event.inputs.RUNNER}}   #tag with your runner tag
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - run: git pull origin ${GITHUB_REF##*/}

      - name: Verification
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.SHARED_DIR}}
          ./verify_preflight.sh

  restore-hub-config:
    needs: pre-flight
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Restore HUB configuraton
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          rsync -avr --progress --delete ${RO_SPOKE_FOLDER}/* ${WORKDIR}/build/

  deploy-spokes:
    needs: pre-flight
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy Spokes
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_SPOKES_DIR}}
          ./render_spokes.sh; sleep 3
          ./deploy.sh

  deploy-icsp-spokes-pre:
    needs: verify-installation
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy ICSP in all the spokes in the Pre flow
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_SPOKES_DIR}}
          ./configure_disconnected.sh 'spoke' 'pre'

  deploy-metallb:
    needs: deploy-icsp-spokes-pre
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy NMState and MetalLB
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_METALLB_DIR}}
          ./deploy.sh

  deploy-ocs:
    needs: deploy-metallb
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy OCS
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_OCS_DIR}}
          ./deploy.sh

  deploy-disconnected-registry-spokes:
    needs: deploy-ocs        # run in parallel with the other jobs
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy Internal Disconnected Registry in each spoke
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_REGISTRY_DIR}}
          ./deploy.sh 'spoke'
          if [ "${{env.SYNC}}" == "yes" ]; then
            ./ocp-sync.sh 'spoke'
            ./olm-sync.sh 'spoke'
          else
            ./mirror-snapshot.sh 'spoke'
          fi
          ./update-global-pullsecret.sh 'spoke'


  deploy-icsp-spokes-post:
    needs: deploy-disconnected-registry-spokes
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy ICSP in all the spokes in the Post flow
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_SPOKES_DIR}}
          ./configure_disconnected.sh 'spoke' 'post'

  deploy-workers:
    needs: deploy-icsp-spokes-post
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy workers
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.DEPLOY_WORKER_DIR}}
          ./render_worker.sh

  dettach_cluster:
    needs: deploy-workers
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy NNCP and detach spoke clusters
        run: |
          export WORKDIR=${GITHUB_WORKSPACE}
          cd ${{env.FINISH_DEP_DIR}}
          ./deploy.sh
