# Enable creating tokenreviews
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-default-rbac
  labels:
    app: ztpfw-ui
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  # name: system:serviceaccount:ztpfw-ui:default
  name: default
  namespace: $UI_NS
